modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Extended%20Bone%20Meal"
logoFile="icon.png"

[[mods]]
modId="extendedbonemeal"
version="3.0"
displayName="Extended Bone Meal"
displayURL="https://curseforge.com/minecraft/mc-mods/extended-bone-meal"
authors="Rick South"
description='''Extends bone meal behaviour. Instant grow with sneak, grow netherwart and other tweaks.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.extendedbonemeal]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"